### ISSUE TITLE
Add support for indicating a primary or secondary reference phylogeny out of all the phylogenies in the Phyx file

### ISSUE THREAD

**Issue by gaurav** [phyloref/klados#133]
As per phyloref/phyloref-ontology#14 and phyloref/phyloref-ontology#16, we can use [`prov:wasDerivedFrom`](https://www.w3.org/TR/prov-o/#wasDerivedFrom) to relate a phyloreference to the PHYX file from which it was generated and/or the original publication from which we curated the phyloreference. We can also use [`has evidence`](http://purl.obolibrary.org/obo/RO_0002558) to link a phyloreference to its reference phylogeny.

In terms of the PHYX file, it's probably fine to keep its current structure. However, these relationships should be generated by `phyx2ontology` when generating the Clade Ontology.

**Comment by gaurav** [comment]
Actually, we do want to record:
- Which phylogeny (if any) is the primary phylogeny for a particular phyloreference.
- Which phylogenies (if any) are secondary phylogenies for a particular phyloreference.

I like the idea of leaving the current structure unchanged (where there is no explicit relationship between every phylogeny and phyloreference). However, the UI should allow the curator to choose a particular phylogeny as a primary or secondary phylogeny. This should be integrated with the new reference phylogeny interface (#70).

**Comment by hlapp** [comment]
I'm a little concerned here about possibly overengineering this at this point? To have a reference to whatever the author(s) used as primary phylogeny seems crucial; what would be the use-case (for phyloreferencing!) to also record a "secondary phylogeny"?

**Comment by gaurav** [comment]
> I'm a little concerned here about possibly overengineering this at this point? To have a reference to whatever the author(s) used as primary phylogeny seems crucial; what would be the use-case (for phyloreferencing!) to also record a "secondary phylogeny"?

As per the Phyx spec, a Phyx file can contain multiple phylogenies, so really the only thing this issue covers is to allow the user to mark a particular phylogeny as the primary reference phyloreference cited in the original clade definition. However, in re-reading this issue, I think it probably would be overengineering to make this machine-readable: this information can be stored in a human-readable form in the curation notes (see #70) or in the phylogeny label or description. I've renamed the issue to clarify this, and unless there's another reason for making that information machine-readable, I think we can close this issue as-is.

**Comment by gaurav** [comment]
For Regnum, per the PhyloCode, a single reference phylogeny is required. But you can list any number of associated phylogenies, which Regnum supports.

- [ ] Gaurav to find examples for why people might want to store multiple phylogenies in the same Phyx file.

Another option would be to make it easy for a user to "swap out" the phylogeny they're interested in working with.
