### ISSUE TITLE
Reactivate ModifiedCard to warn users about exporting the Phyx file

### ISSUE THREAD

**Issue by gaurav** [phyloref/klados#166]
We used to have a ModifiedCard component that displayed a "This phyloreference has changed! Please remember to save it." box above any modified phyloreference (and ditto for phylogenies), but it appears to have been broken by a previous update. It would be nice to have it back so people know that they have to export their Phyx file regularly.

Related to #69.

**Comment by hlapp** [comment]
Yes!!

**Comment by gaurav** [comment]
This seems to be working now. I'll close this for now and reopen if it stops working again (of course, automated tests via #224 would help ensure that this problem is permanently fixed).
