### ISSUE TITLE
Change reasoner URL to reasoner.phyloref.org and set up a Let's Encrypt certificate for it

### ISSUE THREAD

**Issue by gaurav** [phyloref/klados#183]
Our plan is to have the reasoner always at reasoner.phyloref.org, wherever it is actually hosted. It would be nice to have a Let's Encrypt certificate so that all communication with this server is encrypted. I'm not sure how this would work on UF HiperGator, so the first step here is to make reasoner.phyloref.org work on UF HiperGator, and then to make sure that it can work elsewhere.

**Comment by hlapp** [comment]
FYI, the cert does not have to be Let's Encrypt. It does have to be for reasoner.phyloref.org, and it indeed it does have to on the server that first terminates that connection. I.e., if the CNAME where to be changed to a server at UF, that server must terminate the SSL connection with a proper SSL cert for reasoner.phyloref.org.

**Comment by gaurav** [comment]
I did manage to get a Let's Encrypt cert for https://reasoner.phyloref.org/version set up! I'll close this issue once we set this up on UF HiperGator.

**Comment by gaurav** [comment]
This certificate has been up and running for a while now, so I'll go ahead and close this issue.
