### ISSUE TITLE
Bug: when exporting a phylogeny as Newick, spaces in leaf node labels are ignored

### ISSUE THREAD

**Issue by gaurav** [phyloref/klados#200]
There's an odd bug that comes up when using Phylotree to export its phylogeny as Newick: while internal node labels export fine, leaf node label become concatenated with themselves (e.g. "Mitthyridium undulatum" would become "Mitthyridium undulatumMitthyridiumundulatum"). We currently work around this ourselves, but we should come up with a minimum example that shows this issue and post an issue to Phylotree so they can fix it.

**Comment by hlapp** [comment]
I think you can still post it to Phylotree now, and update later if and once we can define a test case? That way they know about its existence, and it's also possible that one of the developers can intuit what the cause might be.

**Comment by gaurav** [comment]
See if Phylotree update fixes it, otherwise remove from Klados v1.0

**Comment by gaurav** [comment]
I've figured out where the bug is in phylotree.js and have reported it to them: https://github.com/veg/phylotree.js/issues/438. They didn't respond in the last week, so I've put in a PR that will fix the issue for us: https://github.com/veg/phylotree.js/pull/441/files

**Comment by gaurav** [comment]
There was a bug in my previous attempt to fix this. I've reported this to phylotree.js at https://github.com/veg/phylotree.js/issues/450 and created a PR to fix it at their end at https://github.com/veg/phylotree.js/pull/448. Once that's fixed, I'll incorporate it in Klados as part of PR https://github.com/phyloref/klados/pull/312 and close this issue.
