### ISSUE TITLE
Add additional example files

### ISSUE THREAD

**Issue by gaurav** [phyloref/klados#232]
In PR #230, I removed the following example files:
* fisher_et_al_2007.json (from https://doi.org/10.1639/0007-2745%282007%29110%5B46%3APOTCWA%5D2.0.CO%3B2)
  - Includes an apomorphy-based definition
* hillis_and_wilcox_2005.json (from https://doi.org/10.1016/j.ympev.2004.10.007)
  - Includes specimen-based definitions
* Most of the phyloreferences from Brochu 2003, replacing it with the minimal version used in the phyx.js tests.

This leaves us with a single small example file, Brochu 2003. This issue tracks us adding additional example files (probably from the Clade Ontology) to Klados. Ideally, they should demonstrate specimen identifiers (like Fisher et al did) or apomorphy-based phyloreferences. Using files from the Clade Ontology will almost certainly be easier than attempting to convert these v0.2.0 files to v1.0.0 Phyloref files.

- [ ] Also check whether phyloreferences with specimens and external references as specifiers can be exported correctly as CSV.

Could be part of the tutorial (#227).

**Comment by gaurav** [comment]
Instead of recreating the old Brochu 2003 (which contained 17 clade definitions and 5 alternate definitions), we could include the 25 clade definitions from [Sangster et al, 2022](https://www.sciencedirect.com/science/article/pii/S2053716622000238), which are open access (under the CC-BY-NC-ND license). Unlike Brochu 2003, however, they don't include their own phylogeny down to the species level showing where they expect these clades to resolve, so we would need to include them separately from [Prum et al. (2015)](https://doi.org/10.1038/nature15697) and [Kuhl et al. (2021)](https://doi.org/10.1093/molbev/msaa191).

**Comment by hlapp** [comment]
Who would curate those definitions? And also, would it be wise to have different example datasets for different software products (if there aren't good reasons as to why one dataset would be much more suitable for one product than another)?

**Comment by gaurav** [comment]
> Who would curate those definitions?

We could use already-curated definitions from the Clade Ontology, as long as we find examples that really exercise Klados. By exercising Klados, I mean:
- Having a variety of publication sources
- Having a variety of phylogenies
- Having a variety of specifier types: concept IRIs, apomorphies, specimens and taxa in a number of nomenclatural codes.

I think the phylorefs we've curated into JSON for the Clade Ontology has examples of all of these except for a variety of publication sources.

> And also, would it be wise to have different example datasets for different software products (if there aren't good reasons as to why one dataset would be much more suitable for one product than another)?

I think there are different needs here: for phyloref.js, we needed something that used a number of Phyx.js features and tested that our Javascript library could process it properly. For the Klados examples, I think we want a number of examples that can show off different functionality in the app -- something we might want to use when demonstrating it to potential users, say. But it would make a lot of sense to move any example Phyx files we generate for this issue into phyloref.js so we can keep checking it during unit tests in that repository.

While working on the tutorial, I found an additional publication that might work as an example:
- Resolving phylogenetic and classical nomenclature: A revision of Seraphsidae Jung, 1974 (Gastropoda: Neostromboidae) -- not open source (Zootaxa)
  - Defines both _Terebellum_ P. F. Röding 1798 [S. J. Maxwell, T. L. Rymer & B. C. Congdon], converted clade name and _Seraphs_ [S. J. Maxwell, T. L. Rymer & B. C. Congdon] 2021, new clade name as sister clades (I think?)

**Comment by gaurav** [comment]
- [ ] Need to put in a disclaimer that the apomorphy-based definitions cannot be resolved on a phylogeny
- [ ] Use one of the apomorphy-based definition from Phylonym
- [ ] Fisher should have a specimen-based definition, so we might be able to meet both needs with a single example
