### ISSUE TITLE
Can't delete phylogeny from phylogeny view

### ISSUE THREAD

**Issue by hlapp** [phyloref/klados#261]
At least in the currently deployed version (refs/tags/v0.3.1), there doesn't seem to be a UI element for deleting a phylogeny. One has to know to go back to the "Summary" option under the Phyloreference section, then scroll down to Phylogenies. That's quite unintuitive.

**Comment by hlapp** [comment]
This issue is still present in deployment `release/v0.4.0`.

**Comment by gaurav** [comment]
Also true for phyloreferences.
