### ISSUE TITLE
CITATION generated citation different (and less informative) than the one given in README

### ISSUE THREAD

**Issue by hlapp** [phyloref/klados#293]
It seems the reason for this is that the `title` field is simply "Klados":
https://github.com/phyloref/klados/blob/a987851221320d8b357d334febfa05d53bb2c0a9/CITATION.cff#L5

Whereas we want this to be *Klados: a tool for authoring, testing and curating phyloreferences*.

The other thing I notice is that the generated BibTeX doesn't include the Zenodo DOI, which seems both unfortunate and undesirable. Any idea how that might be fixed?

**Comment by gaurav** [comment]
Confirmed fixed in a22e1ca.
