### ISSUE TITLE
Improve the Phyx summary page

### ISSUE THREAD

**Issue by gaurav** [phyloref/klados#300]
Two minor fixes may be needed to the Phyx summary page:

1. The phyloref table adds a column for each phylogeny, but currently only uses the label of the phylogeny (e.g. "Fig 1 from Brochu 2003"). Is this clear enough, or should we add "Phylogeny: " to the front of the phylogeny label (e.g. "Phylogeny: Fig 1 from Brochu 2003")?

- [x] If we change this, remember that our default name for unlabeled phylogenies is `Phylogeny 1`, so we want to make sure we don't end up writing this as `Phylogeny: Phylogeny 1`!

https://github.com/phyloref/klados/blob/ce4e31b1de251ff10a22cbc5b2e17ceb41f73436/src/components/phyx/PhyxView.vue#L105-L107

3. The phylogeny table refers to the "Description" of each phylogeny, but this field no longer exists. Should we replace this field with the curator notes? Or some other field, such as the source, number of leaf nodes, list of leaf nodes, etc.?

https://github.com/phyloref/klados/blob/ce4e31b1de251ff10a22cbc5b2e17ceb41f73436/src/components/phyx/PhyxView.vue#L214

<img width="1530" alt="Screenshot 2023-06-21 at 3 27 21 AM" src="https://github.com/phyloref/klados/assets/23979/2f7895fc-407e-41c3-808a-3d92e265a585">

**Comment by hlapp** [comment]
Perhaps prefix with "Phylogeny for ..."? But generally yes for using some prefix.

As for the table, it seems the most natural change would be to remove this column from the table as well. I don't think there's a good reason to maintain the number of columns, and as you implicitly suggest, there is no clear reason by which to select from the list of fields that aren't currently reported the particular field to start reporting in the table.
