### ISSUE TITLE
Mechanism to indicate content is being saved

### ISSUE THREAD

**Issue by GZhang2** [phyloref/klados#69]
Currently, in the specifier editing pop-up window, there isn't a way to know if the content entered is being saved. There is just "close" button, but a novice user cannot know if the content will be saved after he/she hits the "close" button (unless the action is taken).

**Comment by gaurav** [comment]
Reopening. We might want a little thing at the top that notes "Saving" when content is being saved.

**Comment by gaurav** [comment]
What we have (large banner on the top, small exclamation mark next to the "Save" button) seems good enough for current use. If/once Klados is used more widely, we can re-evaluate whether it makes sense to save the Phyx file to the browser in case the browser is closed accidentally or the browser crashes. Closing for now.
