### ISSUE TITLE
Remind users to note whether a clade definition specifies a crown clade in the verbatim definition

### ISSUE THREAD

**Issue by gaurav** [phyloref/klados#71]
In an embargoed curated example, we've found a clade definition whose verbatim definition starts with "The largest crown clade containing ...", even though the clade definition points to the [total or pan group](https://en.wikipedia.org/wiki/Crown_group#Pan-group). Readers are therefore expected to resolve the clade definition, and then exclude the stem groups that would otherwise be included, in order to obtain the [crown group](https://en.wikipedia.org/wiki/Crown_group#Pan-group).

The Curation Tool doesn't currently have a way of indicating that a phyloreference should be restricted to the crown clade, i.e. the reasoner should try to exclude stem groups automatically after resolving the clade definition. This property will require additional annotation of the phylogeny to indicate which terminal groups are extinct, so this issue covers adding that annotation as well.

**Comment by ncellinese** [comment]
I think you are confused here, or I am not sure I understand what you mean. A pan group or total clade is essentially a branch based clade that includes a crown clade rather than just any clade (i.e. a clade with fossils). So what’s the issue here?

Nico

**Comment by gaurav** [comment]
Nico and I just had an in-person discussion about this, and decided that this works better with an example. The actual example comes from clade Angiospermae. In the reference phylogeny, pan-Angiospermae includes four extinct lineages (Glossopterids, Pentoxylon, Bennettitales, Caytonia) and one extant lineage (Angiospermae). If the definition were simply "The largest clade containing ... but not ...", it would resolve to pan-Angiospermae. But since it is "The largest _crown_ clade containing ... but not ...", we need to exclude the four extinct lineages so that we instead resolve to Angiospermae. If we have some way of annotating which terminal nodes are extinct in the phylogeny, we could exclude them after reasoning.

In addition, the clade definition of pan-Angiospermae is simply "the total clade of the crown clade Angiospermae". So, whatever mechanism we develop for excluding extinct lineages, we have to be able to subsequently ignore them if necessary. This would be easiest if carried out after reasoning, but we could also try to find ways to integrate this into the OWL restrictions we use.

**Comment by gaurav** [comment]
The information that a phyloreference should be resolved as a crown clade should probably be included in the curator notes (as we do for the reference taxon information, #70), since this information is not used to construct the logical expressions in OWL in any way. Therefore, I propose that we explicitly note that crown clade status should be included in that field and then close this issue.

**Comment by hlapp** [comment]
We should discuss but I think I agree.

**Comment by gaurav** [comment]
- [ ] Add note to Klados to make it clear that information about clade resolution ("crown" etc.) should be included in the verbatim clade definition.
