### ISSUE TITLE
Find a better way to highlight phylogeny labels that could not be parsed

### ISSUE THREAD

**Issue by gaurav** [phyloref/klados#88]
Currently, if we can't parse a terminal node label in a phylogeny, we highlight it in red as a warning to the curator that the label needs to be corrected. Nico has pointed out that this adds to the visual clutter of the phylogeny display and should be replaced with something simpler.

We could instead display textual errors above the phylogeny, as getErrorsInNewickString() does, or we could create a separate panel for handling multiple taxonomic unit issues, such as recording that a particular node represents multiple taxonomic units in a certain phylogeny (e.g. it might represent species *Panthera tigris*, genus *Panthera* and family Felidae).

**Comment by gaurav** [comment]
Sorry, I should have been clearer! I was referring to the problem we have with phylogenies that contain higher taxa. Since phyloreferences usually have species-based specifiers, we need some way to indicate that a node labeled "Cycadales" on a particular phylogeny includes "Cycas revoluta Thunberg 1782", which would allow us to match it as a specifier. Whether we get this information from ITIS, the Open Tree Taxonomy or another source, we would need to expose this information and its provenance in the Curation Tool UI somewhere -- a separate panel for taxonomic units would be one way to do it! I suggested another way of implementing this at https://github.com/phyloref/curation-tool/issues/45#issuecomment-400831325, but having a dedicated panel for managing all taxonomic units might solve both problems!

**Comment by hlapp** [comment]
> I was referring to the problem we have with phylogenies that contain higher taxa. Since phyloreferences usually have species-based specifiers, we need some way to indicate that a node labeled "Cycadales" on a particular phylogeny includes "Cycas revoluta Thunberg 1782", which would allow us to match it as a specifier.

That's still not quite clear, but perhaps the context about which you are talking about here is where an author uses a specifier in the clade definition that the referenced phylogeny does not include as a label, but where the phylogeny does include a label referring to a larger group that arguably (according to some source, as you say) includes the specifier, and can hence substitute for the specifier.

> Whether we get this information from ITIS, the Open Tree Taxonomy or another source, we would need to expose this information and its provenance in the Curation Tool UI somewhere

I assume you mean this as allowing a user to verify why a node was matched to the specifier? If so, isn't that a problem that goes beyond the curation tool? Wouldn't it be worth thinking about more generally than just for the curation use-case?

**Comment by gaurav** [comment]
We now match higher taxon names without any problem, so this is really just a question of making sure that the curator knows that they're entering taxon names on the phylogeny correctly. I think checking that on input phylogenies is out of scope for what Klados needs to validate. Closing.
